swagger: "2.0"
info:
  title: Aggregator - Partner APIs
  x-ibm-name: aggregator-partner-apis
  version: 1.0.6
  description: JazzCash APIs for Bus Tickets
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
host: $(catalog.host)
schemes:
- https
basePath: /
produces:
- application/json
consumes:
- application/json
security:
- oauthuser:
  - user
securityDefinitions:
  oauthuser:
    type: oauth2
    flow: application
    x-ibm-oauth-provider: oauth-provider-aggregator
    tokenUrl: https://$(catalog.url)/rest/api/v1/aggregator/oauth2/token
    scopes:
      user: Default Scope
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        version: 2.0.0
        title: gatewayscript
        source: context.message.header.set('x-user-metadata',context.get('oauth.verified_access_token.misc_info'));
    - invoke:
        title: invoke
        version: 2.0.0
        verb: keep
        target-url: $(target-url)$(request.path)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blacklist
          values: []
        header-control:
          type: blacklist
          values: []
        inject-proxy-headers: true
  properties:
    target-url:
      value: http://marketplace-microservice.m11s:3000
      description: The URL of the target service
      encoded: false
  activity-log:
    success-content: payload
    error-content: payload
    enabled: true
  application-authentication:
    certificate: false
  catalogs: {}
  buffering: true
definitions:
  notifyRequest:
    type: object
    properties:
      booking_id:
        type: string
      refund_amount:
        type: integer
  notifyResponse:
    type: object
    properties:
      success:
        type: boolean
      response_code:
        type: string
      message:
        type: string
paths:
  /rest/api/v1/aggregator/bus/notify/refund:
    post:
      summary: Notify Bus Ticket Refund
      tags:
      - Bus Tickets
      parameters:
      - in: body
        name: Request Body
        description: Notify Refund Request Body
        schema:
          $ref: '#/definitions/notifyRequest'
      responses:
        "200":
          description: successful request
          schema:
            $ref: '#/definitions/notifyResponse'
  /rest/api/v1/aggregator/event/notify/refund:
    post:
      summary: Notify Event Ticket Refund
      tags:
      - Event Tickets
      parameters:
      - in: body
        name: Request Body
        description: Notify Refund Request Body
        schema:
          $ref: '#/definitions/notifyRequest'
      responses:
        "200":
          description: successful request
          schema:
            $ref: '#/definitions/notifyResponse'
